maestroEspecialista: maestroEspecialista.o
	g++ maestroEspecialista.o -o maestroEspecialista

maestroEspecialista.o: maestroEspecialista.cpp
	g++ -c maestroEspecialista.cpp

clean:
	rm *.o maestroEspecialista